apiVersion: apps/v1
kind: Deployment
metadata:
  name:  cart-microservice
spec:
  selector:
    matchLabels:
      app: cart-microservice
  template:
    metadata:
      labels:
        app: cart-microservice
    spec:
      containers:
      - image: gcr.io/google-samples/microservices-demo/cartservice:v0.8.0
        name:  cart-microservice-container    
        imagePullPolicy: Always
        ports:
        - containerPort:  7070
        env:
        - name: PORT
          value: "7070"
        - name: "REDIS_ADDR"
          value: "redis-service:6379"