apiVersion: apps/v1
kind: Deployment
metadata:
  name:  checkout-microservice
spec:
  selector:
    matchLabels:
      app: checkout-microservice
  template:
    metadata:
      labels:
        app: checkout-microservice
    spec:
      containers:
      - image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.8.0
        name:  checkout-microservice-container    
        imagePullPolicy: Always
        ports:
        - containerPort:  5050
        env:
        - name: PORT
          value: "5050"

        - name: "EMAIL_SERVICE_ADDR"
          value: "email-service:5000"

        - name: "PAYMENT_SERVICE_ADDR"
          value: "payment-service:50051"

        - name: "SHIPPING_SERVICE_ADDR"
          value: "shipping-service:50051"

        - name: "CURRENCY_SERVICE_ADDR"
          value: "currency-service:7000"

        - name: "PRODUCT_CATALOG_SERVICE_ADDR"
          value: "product-catalog-service:3550"

        - name: "CART_SERVICE_ADDR"
          value: "cart-service:7070"