apiVersion: apps/v1
kind: Deployment
metadata:
  name:  currency-microservice
spec:
  selector:
    matchLabels:
      app: currency-microservice
  template:
    metadata:
      labels:
        app: currency-microservice
    spec:
      containers:
      - image:  gcr.io/google-samples/microservices-demo/currencyservice:v0.3.0
        name:  currency-microservice-container    
        imagePullPolicy: Always
        ports:
        - containerPort:  7000
        env:
        - name: PORT
          value: "7000"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_DEBUGGER
          value: "1"