apiVersion: apps/v1
kind: Deployment
metadata:
  name:  email-microservice
spec:
  selector:
    matchLabels:
      app: email-microservice
  template:
    metadata:
      labels:
        app: email-microservice
    spec:
      containers:
      - image:  gcr.io/google-samples/microservices-demo/emailservice:v0.8.0
        name:  email-microservice-container    
        imagePullPolicy: Always
        ports:
        - containerPort:  8080
        env:
          - name: PORT
            value: "8080"
        livenessProbe:
          periodSeconds: 5
          exec:
           command: ["/bin/grpc_health_probe" , "-addr=:8080"]
        readinessProbe:
          periodSeconds: 5
          exec:
           command: ["/bin/grpc_health_probe" , "-addr=:8080"]