apiVersion: apps/v1
kind: Deployment
metadata:
  name:  payment-microservice
spec:
  selector:
    matchLabels:
      app: payment-microservice
  template:
    metadata:
      labels:
        app:  payment-microservice
    spec:
      containers:
      - image:  gcr.io/google-samples/microservices-demo/paymentservice:v0.3.0
        name:  payment-microservice-container   
        imagePullPolicy: Always
        ports:
        - containerPort:  50051
        env:
        - name: PORT 
          value: "50051"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_DEBUGGER
          value: "1"