apiVersion: apps/v1
kind: Deployment
metadata:
  name:  product-catalog-microservice
spec:
  selector:
    matchLabels:
      app: product-catalog-microservice
  template:
    metadata:
      labels:
        app:  product-catalog-microservice
    spec:
      containers:
      - image:  gcr.io/google-samples/microservices-demo/productcatalogservice:v0.8.0
        name:  product-catalog-microservice-container   
        imagePullPolicy: Always 
        ports:
        - containerPort:  3550
        env:
        - name: PORT 
          value: "3550"