microService:
  name: "ad-microservice"
  replicas: "2"
  image: "gcr.io/google-samples/microservices-demo/adservice"
  version: "v0.8.0"
  port: "9555"

containerEnvVars:
- name: "PORT"
  value: "9555"

servicePort: "9555"
serviceType: "ClusterIP"
