microService:
  name: "payment-microservice"
  replicas: "2"
  image: "gcr.io/google-samples/microservices-demo/paymentservice"
  version: "v0.3.0"
  port: "50051"

containerEnvVars:
- name: "PORT"
  value: "50051"
- name: DISABLE_PROFILER
  value: "1"
- name: DISABLE_DEBUGGER
  value: "1"

servicePort: "50051"
serviceType: "ClusterIP"

