microService:
  name: "recommendation-microservice"
  replicas: "2"
  image: "gcr.io/google-samples/microservices-demo/recommendationservice"
  version: "v0.8.0"
  port: "8080"

containerEnvVars:
- name: "PORT"
  value: "8080"
- name: "PRODUCT_CATALOG_SERVICE_ADDR"
  value: "product-catalog-microservice:3550"

servicePort: "8080"
serviceType: "ClusterIP"
