microService:
  name: "shipping-microservice"
  replicas: "2"
  image: "gcr.io/google-samples/microservices-demo/shippingservice"
  version: "v0.8.0"
  port: "50051"

containerEnvVars:
- name: "PORT"
  value: "50051"

servicePort: "50051"
serviceType: "ClusterIP"
