kind: Service
apiVersion: v1
metadata:
  name:  recommendation-service
spec:
  selector:
    app:  recommendation-microservice
  type:  ClusterIP
  ports:
  - protocol:  TCP
    port:  8080
    targetPort:  8080