kind: Service
apiVersion: v1
metadata:
  name:  shipping-service
spec:
  selector:
    app:  shipping-microservice
  type:  ClusterIP
  ports:
  - protocol:  TCP
    port:  50051
    targetPort:  50051